import mongoose, { Document, Schema, Model } from 'mongoose'
import type { AgentId } from '@/lib/config/executives'

// 例会类型
export type StandupType = 'daily' | 'weekly' | 'milestone' | 'adhoc'

// 例会状态
export type StandupStatus = 'scheduled' | 'in_progress' | 'completed' | 'cancelled'

// 议题项
export interface AgendaItem {
  topic: string
  presenter: AgentId
  duration: number // 分钟
  notes?: string
  decisions?: string[]
  actionItems?: Array<{
    task: string
    assignee: AgentId
    dueDate?: Date
  }>
}

// 参会者汇报
export interface ParticipantReport {
  agentId: AgentId
  yesterday?: string      // 昨天完成的工作
  today?: string          // 今天计划的工作
  blockers?: string[]     // 阻碍问题
  highlights?: string[]   // 亮点/成就
  concerns?: string[]     // 关注点
}

// 例会接口
export interface IStandup extends Document {
  _id: mongoose.Types.ObjectId
  userId: mongoose.Types.ObjectId
  projectId: mongoose.Types.ObjectId

  // 基本信息
  type: StandupType
  title: string
  status: StandupStatus

  // 时间
  scheduledAt: Date
  startedAt?: Date
  endedAt?: Date

  // 参与者
  participants: AgentId[]

  // 议题
  agenda: AgendaItem[]

  // 汇报
  reports: ParticipantReport[]

  // 讨论记录
  discussionId?: mongoose.Types.ObjectId

  // 纪要
  minutes?: {
    summary: string
    keyDecisions: string[]
    actionItems: Array<{
      task: string
      assignee: AgentId
      priority: 'high' | 'medium' | 'low'
      dueDate?: Date
    }>
    nextSteps: string[]
    generatedAt: Date
  }

  // 自动化
  isAutoGenerated: boolean
  cronExpression?: string

  createdAt: Date
  updatedAt: Date
}

// 静态方法接口
export interface IStandupModel extends Model<IStandup> {
  scheduleStandup(data: {
    userId: mongoose.Types.ObjectId
    projectId: mongoose.Types.ObjectId
    type: StandupType
    title: string
    scheduledAt: Date
    participants: AgentId[]
    agenda?: AgendaItem[]
    isAutoGenerated?: boolean
    cronExpression?: string
  }): Promise<IStandup>
  getUpcomingStandups(
    userId: mongoose.Types.ObjectId,
    projectId?: mongoose.Types.ObjectId
  ): Promise<IStandup[]>
  getProjectStandups(
    projectId: mongoose.Types.ObjectId,
    limit?: number
  ): Promise<IStandup[]>
  completeStandup(
    standupId: mongoose.Types.ObjectId,
    minutes: IStandup['minutes']
  ): Promise<IStandup | null>
}

// Schema定义
const standupSchema = new Schema<IStandup>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    projectId: {
      type: Schema.Types.ObjectId,
      ref: 'Project',
      required: true,
      index: true,
    },
    type: {
      type: String,
      enum: ['daily', 'weekly', 'milestone', 'adhoc'],
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ['scheduled', 'in_progress', 'completed', 'cancelled'],
      default: 'scheduled',
      index: true,
    },
    scheduledAt: {
      type: Date,
      required: true,
      index: true,
    },
    startedAt: Date,
    endedAt: Date,
    participants: [{
      type: String,
      enum: [
        'mike', 'elena', 'rachel', 'chloe',
        'david', 'james', 'kevin', 'alex',
        'lisa', 'marcus', 'nina', 'sarah',
        'frank', 'tom', 'iris',
        'nathan', 'oscar', 'victor',
      ],
    }],
    agenda: [{
      topic: { type: String, required: true },
      presenter: { type: String, required: true },
      duration: { type: Number, default: 5 },
      notes: String,
      decisions: [String],
      actionItems: [{
        task: String,
        assignee: String,
        dueDate: Date,
      }],
    }],
    reports: [{
      agentId: { type: String, required: true },
      yesterday: String,
      today: String,
      blockers: [String],
      highlights: [String],
      concerns: [String],
    }],
    discussionId: {
      type: Schema.Types.ObjectId,
      ref: 'Discussion',
    },
    minutes: {
      summary: String,
      keyDecisions: [String],
      actionItems: [{
        task: String,
        assignee: String,
        priority: { type: String, enum: ['high', 'medium', 'low'] },
        dueDate: Date,
      }],
      nextSteps: [String],
      generatedAt: Date,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    cronExpression: String,
  },
  {
    timestamps: true,
    collection: 'standups',
  }
)

// 索引
standupSchema.index({ userId: 1, projectId: 1, scheduledAt: -1 })
standupSchema.index({ projectId: 1, status: 1 })
standupSchema.index({ scheduledAt: 1, status: 1 })

// 静态方法: 安排例会
standupSchema.statics.scheduleStandup = async function(data: {
  userId: mongoose.Types.ObjectId
  projectId: mongoose.Types.ObjectId
  type: StandupType
  title: string
  scheduledAt: Date
  participants: AgentId[]
  agenda?: AgendaItem[]
  isAutoGenerated?: boolean
  cronExpression?: string
}): Promise<IStandup> {
  return this.create({
    ...data,
    status: 'scheduled',
    reports: [],
  })
}

// 静态方法: 获取即将进行的例会
standupSchema.statics.getUpcomingStandups = async function(
  userId: mongoose.Types.ObjectId,
  projectId?: mongoose.Types.ObjectId
): Promise<IStandup[]> {
  const query: Record<string, unknown> = {
    userId,
    status: 'scheduled',
    scheduledAt: { $gte: new Date() },
  }
  if (projectId) query.projectId = projectId

  return this.find(query)
    .sort({ scheduledAt: 1 })
    .limit(10)
    .lean()
}

// 静态方法: 获取项目例会记录
standupSchema.statics.getProjectStandups = async function(
  projectId: mongoose.Types.ObjectId,
  limit: number = 20
): Promise<IStandup[]> {
  return this.find({ projectId })
    .sort({ scheduledAt: -1 })
    .limit(limit)
    .lean()
}

// 静态方法: 完成例会
standupSchema.statics.completeStandup = async function(
  standupId: mongoose.Types.ObjectId,
  minutes: IStandup['minutes']
): Promise<IStandup | null> {
  return this.findByIdAndUpdate(
    standupId,
    {
      $set: {
        status: 'completed',
        endedAt: new Date(),
        minutes: {
          ...minutes,
          generatedAt: new Date(),
        },
      },
    },
    { new: true }
  )
}

// 导出模型
export const Standup =
  (mongoose.models.Standup as IStandupModel) ||
  mongoose.model<IStandup, IStandupModel>('Standup', standupSchema)
