import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { connectDB } from '@/lib/db/connect'
import { Standup, Project } from '@/lib/db/models'
import { getExecutive, type AgentId } from '@/lib/config/executives'
import {
  startStandup,
  generateParticipantReports,
  completeStandup,
  scheduleAutoDailyStandup,
} from '@/lib/services/standup-service'
import type { StandupType, AgendaItem } from '@/lib/db/models/standup'

/**
 * GET /api/standups
 * 获取例会列表或单个例会详情
 */
export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    await connectDB()
    const { searchParams } = new URL(req.url)
    const standupId = searchParams.get('id')
    const projectId = searchParams.get('projectId')
    const upcoming = searchParams.get('upcoming') === 'true'

    // 获取单个例会详情
    if (standupId) {
      const standup = await Standup.findOne({
        _id: standupId,
        userId: session.user.id,
      }).populate('projectId', 'name')

      if (!standup) {
        return NextResponse.json(
          { error: 'Standup not found' },
          { status: 404 }
        )
      }

      const project = standup.projectId as any

      return NextResponse.json({
        success: true,
        standup: {
          id: standup._id.toString(),
          projectId: project._id.toString(),
          projectName: project.name,
          type: standup.type,
          title: standup.title,
          status: standup.status,
          scheduledAt: standup.scheduledAt,
          startedAt: standup.startedAt,
          endedAt: standup.endedAt,
          participants: standup.participants.map((p) => {
            const exec = getExecutive(p)
            return {
              id: p,
              name: exec?.nameCn || p,
              title: exec?.titleCn || '',
              avatar: exec?.avatar || '👤',
            }
          }),
          agenda: standup.agenda,
          reports: standup.reports.map((r) => {
            const exec = getExecutive(r.agentId)
            return {
              ...r,
              agentName: exec?.nameCn || r.agentId,
              agentTitle: exec?.titleCn || '',
              agentAvatar: exec?.avatar || '👤',
            }
          }),
          minutes: standup.minutes,
          isAutoGenerated: standup.isAutoGenerated,
        },
      })
    }

    // 获取即将进行的例会
    if (upcoming) {
      const standups = await Standup.getUpcomingStandups(
        session.user.id as any,
        projectId ? (projectId as any) : undefined
      )

      return NextResponse.json({
        success: true,
        standups: standups.map((s) => ({
          id: s._id.toString(),
          projectId: (s.projectId as any).toString(),
          type: s.type,
          title: s.title,
          status: s.status,
          scheduledAt: s.scheduledAt,
          participantsCount: s.participants.length,
        })),
      })
    }

    // 获取项目例会记录
    if (projectId) {
      // 验证项目所有权
      const project = await Project.findOne({
        _id: projectId,
        userId: session.user.id,
      })

      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        )
      }

      const standups = await Standup.getProjectStandups(projectId as any, 20)

      return NextResponse.json({
        success: true,
        standups: standups.map((s) => ({
          id: s._id.toString(),
          type: s.type,
          title: s.title,
          status: s.status,
          scheduledAt: s.scheduledAt,
          endedAt: s.endedAt,
          participantsCount: s.participants.length,
          hasMintes: !!s.minutes,
        })),
      })
    }

    return NextResponse.json(
      { error: 'Missing projectId or id parameter' },
      { status: 400 }
    )
  } catch (error) {
    console.error('Failed to get standups:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

/**
 * POST /api/standups
 * 创建例会或执行例会操作
 */
export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    await connectDB()
    const body = await req.json()
    const { action } = body

    // 安排新例会
    if (action === 'schedule') {
      const { projectId, type, title, scheduledAt, participants, agenda } = body as {
        projectId: string
        type: StandupType
        title: string
        scheduledAt: string
        participants: AgentId[]
        agenda?: AgendaItem[]
      }

      // 验证项目所有权
      const project = await Project.findOne({
        _id: projectId,
        userId: session.user.id,
      })

      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        )
      }

      const standup = await Standup.scheduleStandup({
        userId: session.user.id as any,
        projectId: projectId as any,
        type,
        title,
        scheduledAt: new Date(scheduledAt),
        participants,
        agenda,
        isAutoGenerated: false,
      })

      return NextResponse.json({
        success: true,
        standup: {
          id: standup._id.toString(),
          title: standup.title,
          scheduledAt: standup.scheduledAt,
        },
      })
    }

    // 开启自动每日例会
    if (action === 'enable_auto_daily') {
      const { projectId } = body

      const standup = await scheduleAutoDailyStandup(session.user.id, projectId)

      return NextResponse.json({
        success: true,
        message: '已开启每日例会',
        standup: {
          id: standup._id.toString(),
          scheduledAt: standup.scheduledAt,
        },
      })
    }

    // 开始例会
    if (action === 'start') {
      const { standupId } = body

      // 验证所有权
      const existingStandup = await Standup.findOne({
        _id: standupId,
        userId: session.user.id,
      })

      if (!existingStandup) {
        return NextResponse.json(
          { error: 'Standup not found' },
          { status: 404 }
        )
      }

      const standup = await startStandup(standupId)

      return NextResponse.json({
        success: true,
        standup: {
          id: standup._id.toString(),
          status: standup.status,
          startedAt: standup.startedAt,
        },
      })
    }

    // 生成汇报
    if (action === 'generate_reports') {
      const { standupId } = body

      // 验证所有权
      const existingStandup = await Standup.findOne({
        _id: standupId,
        userId: session.user.id,
      })

      if (!existingStandup) {
        return NextResponse.json(
          { error: 'Standup not found' },
          { status: 404 }
        )
      }

      const reports = await generateParticipantReports(standupId)

      return NextResponse.json({
        success: true,
        reports: reports.map((r) => {
          const exec = getExecutive(r.agentId)
          return {
            ...r,
            agentName: exec?.nameCn || r.agentId,
          }
        }),
      })
    }

    // 完成例会
    if (action === 'complete') {
      const { standupId } = body

      // 验证所有权
      const existingStandup = await Standup.findOne({
        _id: standupId,
        userId: session.user.id,
      })

      if (!existingStandup) {
        return NextResponse.json(
          { error: 'Standup not found' },
          { status: 404 }
        )
      }

      const standup = await completeStandup(standupId)

      return NextResponse.json({
        success: true,
        standup: {
          id: standup._id.toString(),
          status: standup.status,
          endedAt: standup.endedAt,
          minutes: standup.minutes,
        },
      })
    }

    return NextResponse.json(
      { error: 'Invalid action' },
      { status: 400 }
    )
  } catch (error) {
    console.error('Failed to process standup request:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

/**
 * DELETE /api/standups
 * 取消例会
 */
export async function DELETE(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    await connectDB()
    const { searchParams } = new URL(req.url)
    const standupId = searchParams.get('id')

    if (!standupId) {
      return NextResponse.json(
        { error: 'Missing standup id' },
        { status: 400 }
      )
    }

    const standup = await Standup.findOne({
      _id: standupId,
      userId: session.user.id,
    })

    if (!standup) {
      return NextResponse.json(
        { error: 'Standup not found' },
        { status: 404 }
      )
    }

    if (standup.status !== 'scheduled') {
      return NextResponse.json(
        { error: 'Can only cancel scheduled standups' },
        { status: 400 }
      )
    }

    standup.status = 'cancelled'
    await standup.save()

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('Failed to cancel standup:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
