#!/bin/bash
# AI Application Explorer
# Automatically explores the Thinkus app and generates a report

set -e

BASE_URL="${BASE_URL:-http://localhost:3000}"
SESSION_NAME="${SESSION_NAME:-thinkus-explore-$(date +%s)}"
REPORT_FILE="./exploration-report.md"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

ab() {
  agent-browser --session "$SESSION_NAME" "$@"
}

mkdir -p ./screenshots

# Initialize report
cat > "$REPORT_FILE" << 'EOF'
# Thinkus App Exploration Report

Generated by AI Explorer using agent-browser.

## Pages Explored

EOF

echo -e "${BLUE}=== Thinkus App AI Explorer ===${NC}"
echo -e "Base URL: ${YELLOW}$BASE_URL${NC}"
echo ""

# Pages to explore
PAGES=(
  "/"
  "/login"
  "/register"
  "/dashboard"
  "/projects"
  "/create/idea"
  "/create/discuss"
  "/create/confirm"
  "/templates"
  "/pricing"
  "/settings"
  "/settings/profile"
  "/settings/credentials"
  "/settings/notifications"
)

# Explore each page
for page in "${PAGES[@]}"; do
  echo -e "${YELLOW}Exploring: $page${NC}"

  ab open "$BASE_URL$page"
  ab wait 2000

  # Get page info
  title=$(ab get title 2>/dev/null || echo "N/A")
  url=$(ab get url 2>/dev/null || echo "N/A")

  # Get snapshot
  snapshot=$(ab snapshot -c 2>/dev/null || echo "Unable to get snapshot")
  interactive=$(ab snapshot -i 2>/dev/null || echo "")

  # Count elements
  button_count=$(echo "$interactive" | grep -ci "button" || echo "0")
  link_count=$(echo "$interactive" | grep -ci "link" || echo "0")
  input_count=$(echo "$interactive" | grep -ci "textbox\|textarea" || echo "0")

  # Take screenshot
  screenshot_name=$(echo "$page" | tr '/' '-' | sed 's/^-//')
  [ -z "$screenshot_name" ] && screenshot_name="home"
  ab screenshot "./screenshots/explore-$screenshot_name.png" 2>/dev/null || true

  # Add to report
  cat >> "$REPORT_FILE" << EOF

### $page

- **Title**: $title
- **Final URL**: $url
- **Buttons**: $button_count
- **Links**: $link_count
- **Inputs**: $input_count
- **Screenshot**: explore-$screenshot_name.png

**Accessibility Tree (excerpt)**:
\`\`\`
$(echo "$snapshot" | head -20)
\`\`\`

EOF

  echo -e "${GREEN}Done${NC}: $button_count buttons, $link_count links, $input_count inputs"
  echo ""
done

# Generate summary
echo -e "${BLUE}=== Generating Summary ===${NC}"

cat >> "$REPORT_FILE" << EOF

## Summary

- Total pages explored: ${#PAGES[@]}
- Screenshots saved to: ./screenshots/
- Exploration session: $SESSION_NAME

## Notes

- Pages requiring authentication will redirect to /login
- Some elements may be dynamically loaded
- Use specific test scripts for detailed testing

---
*Generated on $(date)*
EOF

# Cleanup
ab close 2>/dev/null || true

echo -e "${GREEN}Exploration complete!${NC}"
echo -e "Report saved to: ${YELLOW}$REPORT_FILE${NC}"
echo -e "Screenshots saved to: ${YELLOW}./screenshots/${NC}"
