# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_employee_pb2 as ai__employee__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_employee_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIEmployeeServiceStub(object):
    """AI Employee Service - Virtual executives for product development
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/thinkus.aiemployee.AIEmployeeService/Chat',
                request_serializer=ai__employee__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/thinkus.aiemployee.AIEmployeeService/ChatStream',
                request_serializer=ai__employee__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.GetEmployee = channel.unary_unary(
                '/thinkus.aiemployee.AIEmployeeService/GetEmployee',
                request_serializer=ai__employee__pb2.GetEmployeeRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.Employee.FromString,
                _registered_method=True)
        self.ListEmployees = channel.unary_unary(
                '/thinkus.aiemployee.AIEmployeeService/ListEmployees',
                request_serializer=ai__employee__pb2.ListEmployeesRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.StartDiscussion = channel.unary_unary(
                '/thinkus.aiemployee.AIEmployeeService/StartDiscussion',
                request_serializer=ai__employee__pb2.StartDiscussionRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.DiscussionResponse.FromString,
                _registered_method=True)
        self.AddToDiscussion = channel.unary_unary(
                '/thinkus.aiemployee.AIEmployeeService/AddToDiscussion',
                request_serializer=ai__employee__pb2.AddToDiscussionRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.DiscussionResponse.FromString,
                _registered_method=True)
        self.GetDiscussion = channel.unary_unary(
                '/thinkus.aiemployee.AIEmployeeService/GetDiscussion',
                request_serializer=ai__employee__pb2.GetDiscussionRequest.SerializeToString,
                response_deserializer=ai__employee__pb2.Discussion.FromString,
                _registered_method=True)


class AIEmployeeServiceServicer(object):
    """AI Employee Service - Virtual executives for product development
    """

    def Chat(self, request, context):
        """Chat with an AI employee
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Chat with streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployee(self, request, context):
        """Get employee information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEmployees(self, request, context):
        """List all available employees
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDiscussion(self, request, context):
        """Start a discussion session with multiple employees
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToDiscussion(self, request, context):
        """Add message to discussion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiscussion(self, request, context):
        """Get discussion history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIEmployeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ai__employee__pb2.ChatRequest.FromString,
                    response_serializer=ai__employee__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=ai__employee__pb2.ChatRequest.FromString,
                    response_serializer=ai__employee__pb2.ChatChunk.SerializeToString,
            ),
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=ai__employee__pb2.GetEmployeeRequest.FromString,
                    response_serializer=ai__employee__pb2.Employee.SerializeToString,
            ),
            'ListEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmployees,
                    request_deserializer=ai__employee__pb2.ListEmployeesRequest.FromString,
                    response_serializer=ai__employee__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'StartDiscussion': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDiscussion,
                    request_deserializer=ai__employee__pb2.StartDiscussionRequest.FromString,
                    response_serializer=ai__employee__pb2.DiscussionResponse.SerializeToString,
            ),
            'AddToDiscussion': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToDiscussion,
                    request_deserializer=ai__employee__pb2.AddToDiscussionRequest.FromString,
                    response_serializer=ai__employee__pb2.DiscussionResponse.SerializeToString,
            ),
            'GetDiscussion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiscussion,
                    request_deserializer=ai__employee__pb2.GetDiscussionRequest.FromString,
                    response_serializer=ai__employee__pb2.Discussion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thinkus.aiemployee.AIEmployeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thinkus.aiemployee.AIEmployeeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIEmployeeService(object):
    """AI Employee Service - Virtual executives for product development
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/Chat',
            ai__employee__pb2.ChatRequest.SerializeToString,
            ai__employee__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/ChatStream',
            ai__employee__pb2.ChatRequest.SerializeToString,
            ai__employee__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/GetEmployee',
            ai__employee__pb2.GetEmployeeRequest.SerializeToString,
            ai__employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/ListEmployees',
            ai__employee__pb2.ListEmployeesRequest.SerializeToString,
            ai__employee__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartDiscussion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/StartDiscussion',
            ai__employee__pb2.StartDiscussionRequest.SerializeToString,
            ai__employee__pb2.DiscussionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToDiscussion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/AddToDiscussion',
            ai__employee__pb2.AddToDiscussionRequest.SerializeToString,
            ai__employee__pb2.DiscussionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiscussion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.aiemployee.AIEmployeeService/GetDiscussion',
            ai__employee__pb2.GetDiscussionRequest.SerializeToString,
            ai__employee__pb2.Discussion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
