# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_services_pb2 as ai__services__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIGuideServiceStub(object):
    """============================================
    AI 产品导游服务
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGuide = channel.unary_unary(
                '/ai.AIGuideService/StartGuide',
                request_serializer=ai__services__pb2.StartGuideRequest.SerializeToString,
                response_deserializer=ai__services__pb2.GuideResponse.FromString,
                _registered_method=True)
        self.ProcessAction = channel.unary_unary(
                '/ai.AIGuideService/ProcessAction',
                request_serializer=ai__services__pb2.ActionRequest.SerializeToString,
                response_deserializer=ai__services__pb2.GuideResponse.FromString,
                _registered_method=True)
        self.AskAI = channel.unary_unary(
                '/ai.AIGuideService/AskAI',
                request_serializer=ai__services__pb2.AskRequest.SerializeToString,
                response_deserializer=ai__services__pb2.AIAnswer.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/ai.AIGuideService/GetSession',
                request_serializer=ai__services__pb2.SessionRequest.SerializeToString,
                response_deserializer=ai__services__pb2.GuideSession.FromString,
                _registered_method=True)


class AIGuideServiceServicer(object):
    """============================================
    AI 产品导游服务
    ============================================

    """

    def StartGuide(self, request, context):
        """开始引导会话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAction(self, request, context):
        """处理用户操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskAI(self, request, context):
        """AI 问答
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """获取会话信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIGuideServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGuide': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGuide,
                    request_deserializer=ai__services__pb2.StartGuideRequest.FromString,
                    response_serializer=ai__services__pb2.GuideResponse.SerializeToString,
            ),
            'ProcessAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAction,
                    request_deserializer=ai__services__pb2.ActionRequest.FromString,
                    response_serializer=ai__services__pb2.GuideResponse.SerializeToString,
            ),
            'AskAI': grpc.unary_unary_rpc_method_handler(
                    servicer.AskAI,
                    request_deserializer=ai__services__pb2.AskRequest.FromString,
                    response_serializer=ai__services__pb2.AIAnswer.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=ai__services__pb2.SessionRequest.FromString,
                    response_serializer=ai__services__pb2.GuideSession.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIGuideService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIGuideService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIGuideService(object):
    """============================================
    AI 产品导游服务
    ============================================

    """

    @staticmethod
    def StartGuide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIGuideService/StartGuide',
            ai__services__pb2.StartGuideRequest.SerializeToString,
            ai__services__pb2.GuideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIGuideService/ProcessAction',
            ai__services__pb2.ActionRequest.SerializeToString,
            ai__services__pb2.GuideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIGuideService/AskAI',
            ai__services__pb2.AskRequest.SerializeToString,
            ai__services__pb2.AIAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIGuideService/GetSession',
            ai__services__pb2.SessionRequest.SerializeToString,
            ai__services__pb2.GuideSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AISupportServiceStub(object):
    """============================================
    AI 智能客服服务
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/ai.AISupportService/Chat',
                request_serializer=ai__services__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__services__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ExecuteFix = channel.unary_unary(
                '/ai.AISupportService/ExecuteFix',
                request_serializer=ai__services__pb2.FixRequest.SerializeToString,
                response_deserializer=ai__services__pb2.FixResponse.FromString,
                _registered_method=True)
        self.AnalyzeScreenshot = channel.unary_unary(
                '/ai.AISupportService/AnalyzeScreenshot',
                request_serializer=ai__services__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=ai__services__pb2.ScreenshotAnalysis.FromString,
                _registered_method=True)
        self.Escalate = channel.unary_unary(
                '/ai.AISupportService/Escalate',
                request_serializer=ai__services__pb2.EscalateRequest.SerializeToString,
                response_deserializer=ai__services__pb2.EscalateResponse.FromString,
                _registered_method=True)


class AISupportServiceServicer(object):
    """============================================
    AI 智能客服服务
    ============================================

    """

    def Chat(self, request, context):
        """发送消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteFix(self, request, context):
        """执行修复
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeScreenshot(self, request, context):
        """分析截图
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Escalate(self, request, context):
        """升级到人工
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AISupportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ai__services__pb2.ChatRequest.FromString,
                    response_serializer=ai__services__pb2.ChatResponse.SerializeToString,
            ),
            'ExecuteFix': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteFix,
                    request_deserializer=ai__services__pb2.FixRequest.FromString,
                    response_serializer=ai__services__pb2.FixResponse.SerializeToString,
            ),
            'AnalyzeScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeScreenshot,
                    request_deserializer=ai__services__pb2.ScreenshotRequest.FromString,
                    response_serializer=ai__services__pb2.ScreenshotAnalysis.SerializeToString,
            ),
            'Escalate': grpc.unary_unary_rpc_method_handler(
                    servicer.Escalate,
                    request_deserializer=ai__services__pb2.EscalateRequest.FromString,
                    response_serializer=ai__services__pb2.EscalateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AISupportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AISupportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AISupportService(object):
    """============================================
    AI 智能客服服务
    ============================================

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AISupportService/Chat',
            ai__services__pb2.ChatRequest.SerializeToString,
            ai__services__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteFix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AISupportService/ExecuteFix',
            ai__services__pb2.FixRequest.SerializeToString,
            ai__services__pb2.FixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AISupportService/AnalyzeScreenshot',
            ai__services__pb2.ScreenshotRequest.SerializeToString,
            ai__services__pb2.ScreenshotAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Escalate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AISupportService/Escalate',
            ai__services__pb2.EscalateRequest.SerializeToString,
            ai__services__pb2.EscalateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AICareServiceStub(object):
    """============================================
    AI 主动关怀服务
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateActivity = channel.unary_unary(
                '/ai.AICareService/UpdateActivity',
                request_serializer=ai__services__pb2.UpdateActivityRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.RecordStuck = channel.unary_unary(
                '/ai.AICareService/RecordStuck',
                request_serializer=ai__services__pb2.StuckRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.GetActivity = channel.unary_unary(
                '/ai.AICareService/GetActivity',
                request_serializer=ai__services__pb2.GetActivityRequest.SerializeToString,
                response_deserializer=ai__services__pb2.UserActivity.FromString,
                _registered_method=True)
        self.GetCareRecords = channel.unary_unary(
                '/ai.AICareService/GetCareRecords',
                request_serializer=ai__services__pb2.CareRecordsRequest.SerializeToString,
                response_deserializer=ai__services__pb2.CareRecordsResponse.FromString,
                _registered_method=True)
        self.TriggerCare = channel.unary_unary(
                '/ai.AICareService/TriggerCare',
                request_serializer=ai__services__pb2.TriggerCareRequest.SerializeToString,
                response_deserializer=ai__services__pb2.TriggerCareResponse.FromString,
                _registered_method=True)


class AICareServiceServicer(object):
    """============================================
    AI 主动关怀服务
    ============================================

    """

    def UpdateActivity(self, request, context):
        """更新用户活动
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordStuck(self, request, context):
        """记录卡住点
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivity(self, request, context):
        """获取用户活动
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCareRecords(self, request, context):
        """获取关怀记录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerCare(self, request, context):
        """手动触发关怀
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AICareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateActivity,
                    request_deserializer=ai__services__pb2.UpdateActivityRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'RecordStuck': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordStuck,
                    request_deserializer=ai__services__pb2.StuckRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'GetActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivity,
                    request_deserializer=ai__services__pb2.GetActivityRequest.FromString,
                    response_serializer=ai__services__pb2.UserActivity.SerializeToString,
            ),
            'GetCareRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCareRecords,
                    request_deserializer=ai__services__pb2.CareRecordsRequest.FromString,
                    response_serializer=ai__services__pb2.CareRecordsResponse.SerializeToString,
            ),
            'TriggerCare': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerCare,
                    request_deserializer=ai__services__pb2.TriggerCareRequest.FromString,
                    response_serializer=ai__services__pb2.TriggerCareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AICareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AICareService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AICareService(object):
    """============================================
    AI 主动关怀服务
    ============================================

    """

    @staticmethod
    def UpdateActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AICareService/UpdateActivity',
            ai__services__pb2.UpdateActivityRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordStuck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AICareService/RecordStuck',
            ai__services__pb2.StuckRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AICareService/GetActivity',
            ai__services__pb2.GetActivityRequest.SerializeToString,
            ai__services__pb2.UserActivity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCareRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AICareService/GetCareRecords',
            ai__services__pb2.CareRecordsRequest.SerializeToString,
            ai__services__pb2.CareRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerCare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AICareService/TriggerCare',
            ai__services__pb2.TriggerCareRequest.SerializeToString,
            ai__services__pb2.TriggerCareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
