# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analytics_pb2 as analytics__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """分析服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Track = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/Track',
                request_serializer=analytics__pb2.TrackRequest.SerializeToString,
                response_deserializer=analytics__pb2.TrackResponse.FromString,
                _registered_method=True)
        self.TrackBatch = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/TrackBatch',
                request_serializer=analytics__pb2.TrackBatchRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/GetStats',
                request_serializer=analytics__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=analytics__pb2.ProjectStats.FromString,
                _registered_method=True)
        self.GetTrends = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/GetTrends',
                request_serializer=analytics__pb2.GetTrendsRequest.SerializeToString,
                response_deserializer=analytics__pb2.TrendResponse.FromString,
                _registered_method=True)
        self.GetFunnel = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/GetFunnel',
                request_serializer=analytics__pb2.GetFunnelRequest.SerializeToString,
                response_deserializer=analytics__pb2.FunnelResponse.FromString,
                _registered_method=True)
        self.GetTopPages = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/GetTopPages',
                request_serializer=analytics__pb2.GetTopPagesRequest.SerializeToString,
                response_deserializer=analytics__pb2.TopPagesResponse.FromString,
                _registered_method=True)
        self.GenerateTrackingScript = channel.unary_unary(
                '/thinkus.analytics.AnalyticsService/GenerateTrackingScript',
                request_serializer=analytics__pb2.ScriptRequest.SerializeToString,
                response_deserializer=analytics__pb2.ScriptResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """分析服务
    """

    def Track(self, request, context):
        """记录事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackBatch(self, request, context):
        """批量记录事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """获取项目统计
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrends(self, request, context):
        """获取趋势数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunnel(self, request, context):
        """获取转化漏斗
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPages(self, request, context):
        """获取热门页面
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTrackingScript(self, request, context):
        """生成跟踪脚本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Track': grpc.unary_unary_rpc_method_handler(
                    servicer.Track,
                    request_deserializer=analytics__pb2.TrackRequest.FromString,
                    response_serializer=analytics__pb2.TrackResponse.SerializeToString,
            ),
            'TrackBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackBatch,
                    request_deserializer=analytics__pb2.TrackBatchRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=analytics__pb2.GetStatsRequest.FromString,
                    response_serializer=analytics__pb2.ProjectStats.SerializeToString,
            ),
            'GetTrends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrends,
                    request_deserializer=analytics__pb2.GetTrendsRequest.FromString,
                    response_serializer=analytics__pb2.TrendResponse.SerializeToString,
            ),
            'GetFunnel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunnel,
                    request_deserializer=analytics__pb2.GetFunnelRequest.FromString,
                    response_serializer=analytics__pb2.FunnelResponse.SerializeToString,
            ),
            'GetTopPages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPages,
                    request_deserializer=analytics__pb2.GetTopPagesRequest.FromString,
                    response_serializer=analytics__pb2.TopPagesResponse.SerializeToString,
            ),
            'GenerateTrackingScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTrackingScript,
                    request_deserializer=analytics__pb2.ScriptRequest.FromString,
                    response_serializer=analytics__pb2.ScriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thinkus.analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thinkus.analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """分析服务
    """

    @staticmethod
    def Track(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/Track',
            analytics__pb2.TrackRequest.SerializeToString,
            analytics__pb2.TrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/TrackBatch',
            analytics__pb2.TrackBatchRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/GetStats',
            analytics__pb2.GetStatsRequest.SerializeToString,
            analytics__pb2.ProjectStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/GetTrends',
            analytics__pb2.GetTrendsRequest.SerializeToString,
            analytics__pb2.TrendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFunnel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/GetFunnel',
            analytics__pb2.GetFunnelRequest.SerializeToString,
            analytics__pb2.FunnelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/GetTopPages',
            analytics__pb2.GetTopPagesRequest.SerializeToString,
            analytics__pb2.TopPagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTrackingScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.AnalyticsService/GenerateTrackingScript',
            analytics__pb2.ScriptRequest.SerializeToString,
            analytics__pb2.ScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RealtimeServiceStub(object):
    """实时流服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/thinkus.analytics.RealtimeService/Subscribe',
                request_serializer=analytics__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=analytics__pb2.StreamEvent.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/thinkus.analytics.RealtimeService/Push',
                request_serializer=analytics__pb2.PushEventRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)


class RealtimeServiceServicer(object):
    """实时流服务
    """

    def Subscribe(self, request, context):
        """订阅项目事件流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """推送事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealtimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=analytics__pb2.SubscribeRequest.FromString,
                    response_serializer=analytics__pb2.StreamEvent.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=analytics__pb2.PushEventRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thinkus.analytics.RealtimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thinkus.analytics.RealtimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RealtimeService(object):
    """实时流服务
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/thinkus.analytics.RealtimeService/Subscribe',
            analytics__pb2.SubscribeRequest.SerializeToString,
            analytics__pb2.StreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.analytics.RealtimeService/Push',
            analytics__pb2.PushEventRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
