# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import document_pb2 as document__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """文档处理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFiles = channel.unary_unary(
                '/thinkus.document.DocumentService/ProcessFiles',
                request_serializer=document__pb2.ProcessFilesRequest.SerializeToString,
                response_deserializer=document__pb2.ProcessFilesResponse.FromString,
                _registered_method=True)
        self.ProcessURL = channel.unary_unary(
                '/thinkus.document.DocumentService/ProcessURL',
                request_serializer=document__pb2.ProcessURLRequest.SerializeToString,
                response_deserializer=document__pb2.ProcessedResult.FromString,
                _registered_method=True)
        self.IntegrateRequirements = channel.unary_unary(
                '/thinkus.document.DocumentService/IntegrateRequirements',
                request_serializer=document__pb2.IntegrateRequest.SerializeToString,
                response_deserializer=document__pb2.IntegratedRequirement.FromString,
                _registered_method=True)
        self.GenerateGrowthAdvice = channel.unary_unary(
                '/thinkus.document.DocumentService/GenerateGrowthAdvice',
                request_serializer=document__pb2.GrowthAdviceRequest.SerializeToString,
                response_deserializer=document__pb2.GrowthAdviceResponse.FromString,
                _registered_method=True)
        self.MatchExperience = channel.unary_unary(
                '/thinkus.document.DocumentService/MatchExperience',
                request_serializer=document__pb2.ExperienceMatchRequest.SerializeToString,
                response_deserializer=document__pb2.ExperienceMatchResponse.FromString,
                _registered_method=True)
        self.AddExperience = channel.unary_unary(
                '/thinkus.document.DocumentService/AddExperience',
                request_serializer=document__pb2.AddExperienceRequest.SerializeToString,
                response_deserializer=document__pb2.Experience.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """文档处理服务
    """

    def ProcessFiles(self, request, context):
        """处理上传的文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessURL(self, request, context):
        """处理 URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntegrateRequirements(self, request, context):
        """整合需求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateGrowthAdvice(self, request, context):
        """生成增长建议
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchExperience(self, request, context):
        """匹配经验
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddExperience(self, request, context):
        """添加经验
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFiles,
                    request_deserializer=document__pb2.ProcessFilesRequest.FromString,
                    response_serializer=document__pb2.ProcessFilesResponse.SerializeToString,
            ),
            'ProcessURL': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessURL,
                    request_deserializer=document__pb2.ProcessURLRequest.FromString,
                    response_serializer=document__pb2.ProcessedResult.SerializeToString,
            ),
            'IntegrateRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.IntegrateRequirements,
                    request_deserializer=document__pb2.IntegrateRequest.FromString,
                    response_serializer=document__pb2.IntegratedRequirement.SerializeToString,
            ),
            'GenerateGrowthAdvice': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateGrowthAdvice,
                    request_deserializer=document__pb2.GrowthAdviceRequest.FromString,
                    response_serializer=document__pb2.GrowthAdviceResponse.SerializeToString,
            ),
            'MatchExperience': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchExperience,
                    request_deserializer=document__pb2.ExperienceMatchRequest.FromString,
                    response_serializer=document__pb2.ExperienceMatchResponse.SerializeToString,
            ),
            'AddExperience': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExperience,
                    request_deserializer=document__pb2.AddExperienceRequest.FromString,
                    response_serializer=document__pb2.Experience.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thinkus.document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thinkus.document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """文档处理服务
    """

    @staticmethod
    def ProcessFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.document.DocumentService/ProcessFiles',
            document__pb2.ProcessFilesRequest.SerializeToString,
            document__pb2.ProcessFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.document.DocumentService/ProcessURL',
            document__pb2.ProcessURLRequest.SerializeToString,
            document__pb2.ProcessedResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntegrateRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.document.DocumentService/IntegrateRequirements',
            document__pb2.IntegrateRequest.SerializeToString,
            document__pb2.IntegratedRequirement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateGrowthAdvice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.document.DocumentService/GenerateGrowthAdvice',
            document__pb2.GrowthAdviceRequest.SerializeToString,
            document__pb2.GrowthAdviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchExperience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.document.DocumentService/MatchExperience',
            document__pb2.ExperienceMatchRequest.SerializeToString,
            document__pb2.ExperienceMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddExperience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.document.DocumentService/AddExperience',
            document__pb2.AddExperienceRequest.SerializeToString,
            document__pb2.Experience.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
