# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """沙盒管理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Create',
                request_serializer=sandbox__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.GetOrCreate = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/GetOrCreate',
                request_serializer=sandbox__pb2.GetOrCreateRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Get',
                request_serializer=sandbox__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Exec',
                request_serializer=sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecResult.FromString,
                _registered_method=True)
        self.ExecStream = channel.unary_stream(
                '/thinkus.sandbox.SandboxService/ExecStream',
                request_serializer=sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/WriteFile',
                request_serializer=sandbox__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/ReadFile',
                request_serializer=sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=sandbox__pb2.FileContent.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/ListFiles',
                request_serializer=sandbox__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Pause',
                request_serializer=sandbox__pb2.SandboxIdRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Resume',
                request_serializer=sandbox__pb2.SandboxIdRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Destroy',
                request_serializer=sandbox__pb2.SandboxIdRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.Export = channel.unary_unary(
                '/thinkus.sandbox.SandboxService/Export',
                request_serializer=sandbox__pb2.SandboxIdRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExportResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/thinkus.sandbox.SandboxService/SubscribeEvents',
                request_serializer=sandbox__pb2.SandboxIdRequest.SerializeToString,
                response_deserializer=sandbox__pb2.SandboxEvent.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """沙盒管理服务
    """

    def Create(self, request, context):
        """创建沙盒
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrCreate(self, request, context):
        """获取或创建沙盒
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """获取沙盒信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """执行命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecStream(self, request, context):
        """流式执行命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """写文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """读文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """列出文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """暂停沙盒
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """恢复沙盒
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """销毁沙盒
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """导出沙盒
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """订阅沙盒事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=sandbox__pb2.CreateSandboxRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'GetOrCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrCreate,
                    request_deserializer=sandbox__pb2.GetOrCreateRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=sandbox__pb2.GetSandboxRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecResult.SerializeToString,
            ),
            'ExecStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecStream,
                    request_deserializer=sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecOutput.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=sandbox__pb2.WriteFileRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=sandbox__pb2.FileContent.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=sandbox__pb2.ListFilesRequest.FromString,
                    response_serializer=sandbox__pb2.ListFilesResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=sandbox__pb2.SandboxIdRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=sandbox__pb2.SandboxIdRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=sandbox__pb2.SandboxIdRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Export': grpc.unary_unary_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=sandbox__pb2.SandboxIdRequest.FromString,
                    response_serializer=sandbox__pb2.ExportResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=sandbox__pb2.SandboxIdRequest.FromString,
                    response_serializer=sandbox__pb2.SandboxEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thinkus.sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thinkus.sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """沙盒管理服务
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Create',
            sandbox__pb2.CreateSandboxRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/GetOrCreate',
            sandbox__pb2.GetOrCreateRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Get',
            sandbox__pb2.GetSandboxRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Exec',
            sandbox__pb2.ExecRequest.SerializeToString,
            sandbox__pb2.ExecResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/thinkus.sandbox.SandboxService/ExecStream',
            sandbox__pb2.ExecRequest.SerializeToString,
            sandbox__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/WriteFile',
            sandbox__pb2.WriteFileRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/ReadFile',
            sandbox__pb2.ReadFileRequest.SerializeToString,
            sandbox__pb2.FileContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/ListFiles',
            sandbox__pb2.ListFilesRequest.SerializeToString,
            sandbox__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Pause',
            sandbox__pb2.SandboxIdRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Resume',
            sandbox__pb2.SandboxIdRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Destroy',
            sandbox__pb2.SandboxIdRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkus.sandbox.SandboxService/Export',
            sandbox__pb2.SandboxIdRequest.SerializeToString,
            sandbox__pb2.ExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/thinkus.sandbox.SandboxService/SubscribeEvents',
            sandbox__pb2.SandboxIdRequest.SerializeToString,
            sandbox__pb2.SandboxEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
