FROM golang:1.22-alpine

WORKDIR /app

# Install tools
RUN apk add --no-cache git protobuf protobuf-dev docker-cli && \
    go install github.com/air-verse/air@latest && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

COPY go.mod go.sum ./
RUN go mod download

ENV GRPC_PORT=50053

EXPOSE 50053

CMD ["air", "-c", ".air.toml"]
