'use client'

import { useState, useEffect, useCallback } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Skeleton } from '@/components/ui/skeleton'
import { Separator } from '@/components/ui/separator'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion'
import { useToast } from '@/components/ui/use-toast'
import {
  Calendar,
  Clock,
  Users,
  Play,
  CheckCircle2,
  FileText,
  AlertCircle,
  Sparkles,
  Loader2,
  ChevronRight,
  Target,
  TrendingUp,
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface Participant {
  id: string
  name: string
  title: string
  avatar: string
}

interface Report {
  agentId: string
  agentName: string
  agentTitle: string
  agentAvatar: string
  yesterday?: string
  today?: string
  blockers?: string[]
  highlights?: string[]
  concerns?: string[]
}

interface Minutes {
  summary: string
  keyDecisions: string[]
  actionItems: Array<{
    task: string
    assignee: string
    priority: string
    dueDate?: string
  }>
  nextSteps: string[]
  generatedAt: string
}

interface Standup {
  id: string
  projectId: string
  projectName: string
  type: string
  title: string
  status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled'
  scheduledAt: string
  startedAt?: string
  endedAt?: string
  participants: Participant[]
  reports: Report[]
  minutes?: Minutes
  isAutoGenerated: boolean
}

interface StandupListItem {
  id: string
  type: string
  title: string
  status: string
  scheduledAt: string
  endedAt?: string
  participantsCount: number
  hasMinutes?: boolean
}

interface StandupPanelProps {
  projectId: string
}

export function StandupPanel({ projectId }: StandupPanelProps) {
  const { toast } = useToast()
  const [standups, setStandups] = useState<StandupListItem[]>([])
  const [selectedStandup, setSelectedStandup] = useState<Standup | null>(null)
  const [loading, setLoading] = useState(true)
  const [detailLoading, setDetailLoading] = useState(false)
  const [actionLoading, setActionLoading] = useState<string | null>(null)
  const [detailDialogOpen, setDetailDialogOpen] = useState(false)

  // 加载例会列表
  const loadStandups = useCallback(async () => {
    try {
      setLoading(true)
      const response = await fetch(`/api/standups?projectId=${projectId}`)
      const data = await response.json()
      if (data.success) {
        setStandups(data.standups || [])
      }
    } catch (error) {
      console.error('Failed to load standups:', error)
      toast({
        title: '加载失败',
        description: '无法加载例会列表',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }, [projectId, toast])

  useEffect(() => {
    loadStandups()
  }, [loadStandups])

  // 加载例会详情
  const loadStandupDetail = async (standupId: string) => {
    try {
      setDetailLoading(true)
      const response = await fetch(`/api/standups?id=${standupId}`)
      const data = await response.json()
      if (data.success) {
        setSelectedStandup(data.standup)
        setDetailDialogOpen(true)
      }
    } catch (error) {
      console.error('Failed to load standup detail:', error)
      toast({
        title: '加载失败',
        description: '无法加载例会详情',
        variant: 'destructive',
      })
    } finally {
      setDetailLoading(false)
    }
  }

  // 开启自动每日例会
  const enableAutoDailyStandup = async () => {
    try {
      setActionLoading('enable_auto')
      const response = await fetch('/api/standups', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'enable_auto_daily',
          projectId,
        }),
      })

      const data = await response.json()
      if (data.success) {
        toast({
          title: '已开启每日例会',
          description: '系统将自动在每个工作日早上9点安排例会',
        })
        loadStandups()
      } else {
        throw new Error(data.error)
      }
    } catch (error) {
      console.error('Failed to enable auto standup:', error)
      toast({
        title: '操作失败',
        description: '无法开启自动例会',
        variant: 'destructive',
      })
    } finally {
      setActionLoading(null)
    }
  }

  // 开始例会
  const handleStartStandup = async (standupId: string) => {
    try {
      setActionLoading(standupId)

      // 开始例会
      await fetch('/api/standups', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'start', standupId }),
      })

      // 生成汇报
      await fetch('/api/standups', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'generate_reports', standupId }),
      })

      // 完成例会
      const response = await fetch('/api/standups', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'complete', standupId }),
      })

      const data = await response.json()
      if (data.success) {
        toast({
          title: '例会已完成',
          description: '会议纪要已生成',
        })
        loadStandups()
        // 显示详情
        loadStandupDetail(standupId)
      } else {
        throw new Error(data.error)
      }
    } catch (error) {
      console.error('Failed to run standup:', error)
      toast({
        title: '例会执行失败',
        description: '请稍后重试',
        variant: 'destructive',
      })
    } finally {
      setActionLoading(null)
    }
  }

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleString('zh-CN', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const getStatusBadge = (status: string) => {
    const config: Record<string, { label: string; variant: 'default' | 'secondary' | 'outline' | 'destructive' }> = {
      scheduled: { label: '已安排', variant: 'secondary' },
      in_progress: { label: '进行中', variant: 'default' },
      completed: { label: '已完成', variant: 'outline' },
      cancelled: { label: '已取消', variant: 'destructive' },
    }
    const { label, variant } = config[status] || { label: status, variant: 'outline' as const }
    return <Badge variant={variant}>{label}</Badge>
  }

  const getTypeLabel = (type: string) => {
    const labels: Record<string, string> = {
      daily: '每日例会',
      weekly: '周例会',
      milestone: '里程碑会议',
      adhoc: '临时会议',
    }
    return labels[type] || type
  }

  if (loading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-32" />
        <Skeleton className="h-32" />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* 头部 */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Calendar className="h-6 w-6 text-primary" />
          <div>
            <h2 className="text-xl font-semibold">项目例会</h2>
            <p className="text-sm text-muted-foreground">
              AI高管团队的定期会议和纪要
            </p>
          </div>
        </div>
        <Button
          onClick={enableAutoDailyStandup}
          disabled={actionLoading === 'enable_auto'}
        >
          {actionLoading === 'enable_auto' ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Sparkles className="h-4 w-4 mr-2" />
          )}
          开启每日例会
        </Button>
      </div>

      {/* 例会列表 */}
      {standups.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Calendar className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <p className="text-muted-foreground">暂无例会记录</p>
            <p className="text-sm text-muted-foreground mt-1">
              开启每日例会让AI高管团队定期同步进度
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {standups.map((standup) => (
            <Card
              key={standup.id}
              className="cursor-pointer hover:shadow-md transition-shadow"
              onClick={() => loadStandupDetail(standup.id)}
            >
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div
                      className={cn(
                        'w-10 h-10 rounded-full flex items-center justify-center',
                        standup.status === 'completed'
                          ? 'bg-green-100 text-green-600'
                          : standup.status === 'scheduled'
                          ? 'bg-blue-100 text-blue-600'
                          : 'bg-muted'
                      )}
                    >
                      {standup.status === 'completed' ? (
                        <CheckCircle2 className="h-5 w-5" />
                      ) : (
                        <Calendar className="h-5 w-5" />
                      )}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-medium">{standup.title}</span>
                        {getStatusBadge(standup.status)}
                      </div>
                      <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                        <span className="flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {formatDate(standup.scheduledAt)}
                        </span>
                        <span className="flex items-center gap-1">
                          <Users className="h-3 w-3" />
                          {standup.participantsCount} 人
                        </span>
                        <Badge variant="outline" className="text-xs">
                          {getTypeLabel(standup.type)}
                        </Badge>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {standup.status === 'scheduled' && (
                      <Button
                        size="sm"
                        onClick={(e) => {
                          e.stopPropagation()
                          handleStartStandup(standup.id)
                        }}
                        disabled={actionLoading === standup.id}
                      >
                        {actionLoading === standup.id ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          <>
                            <Play className="h-4 w-4 mr-1" />
                            开始
                          </>
                        )}
                      </Button>
                    )}
                    <ChevronRight className="h-5 w-5 text-muted-foreground" />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* 详情对话框 */}
      <Dialog open={detailDialogOpen} onOpenChange={setDetailDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-hidden flex flex-col">
          {detailLoading ? (
            <div className="py-12 flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin" />
            </div>
          ) : selectedStandup ? (
            <>
              <DialogHeader>
                <div className="flex items-center gap-2 mb-2">
                  {getStatusBadge(selectedStandup.status)}
                  <Badge variant="outline">{getTypeLabel(selectedStandup.type)}</Badge>
                </div>
                <DialogTitle>{selectedStandup.title}</DialogTitle>
                <DialogDescription>
                  {formatDate(selectedStandup.scheduledAt)} · {selectedStandup.projectName}
                </DialogDescription>
              </DialogHeader>

              <ScrollArea className="flex-1 pr-4">
                <div className="space-y-6">
                  {/* 参会人员 */}
                  <div>
                    <h4 className="font-medium mb-3 flex items-center gap-2">
                      <Users className="h-4 w-4" />
                      参会人员
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {selectedStandup.participants.map((p) => (
                        <div
                          key={p.id}
                          className="flex items-center gap-2 bg-muted rounded-full px-3 py-1"
                        >
                          <span>{p.avatar}</span>
                          <span className="text-sm">{p.name}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <Separator />

                  {/* 汇报内容 */}
                  {selectedStandup.reports.length > 0 && (
                    <div>
                      <h4 className="font-medium mb-3 flex items-center gap-2">
                        <FileText className="h-4 w-4" />
                        成员汇报
                      </h4>
                      <Accordion type="single" collapsible className="w-full">
                        {selectedStandup.reports.map((report) => (
                          <AccordionItem key={report.agentId} value={report.agentId}>
                            <AccordionTrigger className="hover:no-underline">
                              <div className="flex items-center gap-2">
                                <span className="text-lg">{report.agentAvatar}</span>
                                <span>{report.agentName}</span>
                                <span className="text-xs text-muted-foreground">
                                  {report.agentTitle}
                                </span>
                              </div>
                            </AccordionTrigger>
                            <AccordionContent>
                              <div className="space-y-3 pl-8">
                                {report.yesterday && (
                                  <div>
                                    <p className="text-sm font-medium text-muted-foreground">昨日工作</p>
                                    <p className="text-sm">{report.yesterday}</p>
                                  </div>
                                )}
                                {report.today && (
                                  <div>
                                    <p className="text-sm font-medium text-muted-foreground">今日计划</p>
                                    <p className="text-sm">{report.today}</p>
                                  </div>
                                )}
                                {report.blockers && report.blockers.length > 0 && (
                                  <div>
                                    <p className="text-sm font-medium text-destructive flex items-center gap-1">
                                      <AlertCircle className="h-3 w-3" />
                                      阻碍问题
                                    </p>
                                    <ul className="text-sm list-disc pl-4">
                                      {report.blockers.map((b, i) => (
                                        <li key={i}>{b}</li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                                {report.highlights && report.highlights.length > 0 && (
                                  <div>
                                    <p className="text-sm font-medium text-green-600 flex items-center gap-1">
                                      <TrendingUp className="h-3 w-3" />
                                      亮点
                                    </p>
                                    <ul className="text-sm list-disc pl-4">
                                      {report.highlights.map((h, i) => (
                                        <li key={i}>{h}</li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                              </div>
                            </AccordionContent>
                          </AccordionItem>
                        ))}
                      </Accordion>
                    </div>
                  )}

                  {/* 会议纪要 */}
                  {selectedStandup.minutes && (
                    <>
                      <Separator />
                      <div>
                        <h4 className="font-medium mb-3 flex items-center gap-2">
                          <Target className="h-4 w-4" />
                          会议纪要
                        </h4>
                        <div className="space-y-4">
                          <div>
                            <p className="text-sm font-medium text-muted-foreground mb-1">总结</p>
                            <p className="text-sm">{selectedStandup.minutes.summary}</p>
                          </div>

                          {selectedStandup.minutes.keyDecisions.length > 0 && (
                            <div>
                              <p className="text-sm font-medium text-muted-foreground mb-1">关键决策</p>
                              <ul className="text-sm list-disc pl-4">
                                {selectedStandup.minutes.keyDecisions.map((d, i) => (
                                  <li key={i}>{d}</li>
                                ))}
                              </ul>
                            </div>
                          )}

                          {selectedStandup.minutes.actionItems.length > 0 && (
                            <div>
                              <p className="text-sm font-medium text-muted-foreground mb-1">行动项</p>
                              <div className="space-y-2">
                                {selectedStandup.minutes.actionItems.map((item, i) => (
                                  <div
                                    key={i}
                                    className="flex items-center gap-2 text-sm bg-muted p-2 rounded"
                                  >
                                    <Badge
                                      variant={
                                        item.priority === 'high'
                                          ? 'destructive'
                                          : item.priority === 'medium'
                                          ? 'default'
                                          : 'secondary'
                                      }
                                      className="text-xs"
                                    >
                                      {item.priority}
                                    </Badge>
                                    <span className="flex-1">{item.task}</span>
                                    <span className="text-muted-foreground">@{item.assignee}</span>
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}

                          {selectedStandup.minutes.nextSteps.length > 0 && (
                            <div>
                              <p className="text-sm font-medium text-muted-foreground mb-1">下一步</p>
                              <ul className="text-sm list-disc pl-4">
                                {selectedStandup.minutes.nextSteps.map((s, i) => (
                                  <li key={i}>{s}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    </>
                  )}
                </div>
              </ScrollArea>

              <DialogFooter>
                <Button variant="outline" onClick={() => setDetailDialogOpen(false)}>
                  关闭
                </Button>
              </DialogFooter>
            </>
          ) : null}
        </DialogContent>
      </Dialog>
    </div>
  )
}
